// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRGlfxdeR22WX4gPF2Im7YLiH9k9QskwA',
    appId: '1:337730650555:web:f9629f09774e07edbcc49e',
    messagingSenderId: '337730650555',
    projectId: 'emotionsandcareal',
    authDomain: 'emotionsandcareal.firebaseapp.com',
    storageBucket: 'emotionsandcareal.appspot.com',
    measurementId: 'G-906S1H6J2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHKnCAcbYf0FRGGUAuZfmioP7d1WIp8Ag',
    appId: '1:337730650555:android:7219ef3af2acb372bcc49e',
    messagingSenderId: '337730650555',
    projectId: 'emotionsandcareal',
    storageBucket: 'emotionsandcareal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvJL1Hkd2DEScTP6TFPpnpjo24MDJrLw8',
    appId: '1:337730650555:ios:5705cc499b2040cbbcc49e',
    messagingSenderId: '337730650555',
    projectId: 'emotionsandcareal',
    storageBucket: 'emotionsandcareal.appspot.com',
    iosClientId:
        '337730650555-dgac5q7gc4sa6nqm742jrntdo2bhd0jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.emotionsandcare',
  );
}

// web       1:337730650555:web:f9629f09774e07edbcc49e
// android   1:337730650555:android:7219ef3af2acb372bcc49e
// ios       1:337730650555:ios:5705cc499b2040cbbcc49e