// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRGlfxdeR22WX4gPF2Im7YLiH9k9QskwA',
    appId: '1:337730650555:web:f9629f09774e07edbcc49e',
    messagingSenderId: '337730650555',
    projectId: 'emotionsandcareal',
    authDomain: 'emotionsandcareal.firebaseapp.com',
    storageBucket: 'emotionsandcareal.appspot.com',
    measurementId: 'G-906S1H6J2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRGlfxdeR22WX4gPF2Im7YLiH9k9QskwA',
    appId: '1:337730650555:android:0223342204b1cf2ebcc49e',
    messagingSenderId: '337730650555',
    projectId: 'emotionsandcareal',
    storageBucket: 'emotionsandcareal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvJL1Hkd2DEScTP6TFPpnpjo24MDJrLw8',
    appId: '1:337730650555:ios:94bbde6931b348cebcc49e',
    messagingSenderId: '337730650555',
    projectId: 'emotionsandcareal',
    storageBucket: 'emotionsandcareal.appspot.com',
    iosClientId:
        '337730650555-ni26o23adgai1gf6udgkqka9tm3fnuv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.emotionsAndCareV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvJL1Hkd2DEScTP6TFPpnpjo24MDJrLw8',
    appId: '1:337730650555:ios:94bbde6931b348cebcc49e',
    messagingSenderId: '337730650555',
    projectId: 'emotionsandcareal',
    storageBucket: 'emotionsandcareal.appspot.com',
    iosClientId:
        '337730650555-ni26o23adgai1gf6udgkqka9tm3fnuv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.emotionsAndCareV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrllJWzrXapWzpBvX6dJc4PTfExt3DvfE',
    appId: '1:337730650555:web:f4c4ba52c57c2070bcc49e',
    messagingSenderId: '337730650555',
    projectId: 'emotionsandcareal',
    authDomain: 'emotionsandcareal.firebaseapp.com',
    storageBucket: 'emotionsandcareal.appspot.com',
    measurementId: 'G-JBDSEDSCFK',
  );
}
